// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineBinaryExpressionEvaluator.Models;

namespace OnlineBinaryExpressionEvaluator.Migrations
{
    [DbContext(typeof(OnlineBinaryExpressionEvaluatorContext))]
    [Migration("20190918190717_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OnlineBinaryExpressionEvaluator.Models.BinaryAddition", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AdditionResult")
                        .HasMaxLength(8);

                    b.Property<string>("Operand1")
                        .HasMaxLength(7);

                    b.Property<string>("Operand2")
                        .HasMaxLength(7);

                    b.HasKey("ID");

                    b.ToTable("BinaryAddition");
                });

            modelBuilder.Entity("OnlineBinaryExpressionEvaluator.Models.BinaryMultiplication", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MultiplicationResult")
                        .HasMaxLength(8);

                    b.Property<string>("Operand1")
                        .HasMaxLength(4);

                    b.Property<string>("Operand2")
                        .HasMaxLength(4);

                    b.HasKey("ID");

                    b.ToTable("BinaryMultiplication");
                });

            modelBuilder.Entity("OnlineBinaryExpressionEvaluator.Models.BinaryNegation", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NegationResult")
                        .HasMaxLength(8);

                    b.Property<string>("Operand")
                        .HasMaxLength(7);

                    b.HasKey("ID");

                    b.ToTable("BinaryNegation");
                });
#pragma warning restore 612, 618
        }
    }
}
