// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineBinaryExpressionEvaluator.Models;

namespace OnlineBinaryExpressionEvaluator.Migrations
{
    [DbContext(typeof(OnlineBinaryExpressionEvaluatorContext))]
    [Migration("20190913023828_NegationResult2")]
    partial class NegationResult2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OnlineBinaryExpressionEvaluator.Models.Expression", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AdditionResult");

                    b.Property<string>("MultiplicationResult");

                    b.Property<string>("NegationResult1");

                    b.Property<string>("NegationResult2");

                    b.Property<string>("Operand1");

                    b.Property<string>("Operand2");

                    b.HasKey("ID");

                    b.ToTable("Expression");
                });
#pragma warning restore 612, 618
        }
    }
}
